#set zsh configs and initial stuff
set -g default-terminal xterm-256color
set-option -g default-shell $SHELL
set-option -g default-command "exec zsh"
set -g status-keys vi
set -g mouse on

#prefix key
set-option -g prefix C-d
set-option -g prefix2 C-j
unbind-key C-d
bind-key C-j send-prefix
set -g base-index 1

# Use Alt-arrow keys without prefix key to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Set easier window split keys
bind-key v split-window -h
bind-key h split-window -v


# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# Easily reorder windows with CTRL+SHIFT+Arrow
bind-key -n C-S-Left swap-window -t -1
bind-key -n C-S-Right swap-window -t +1

# Synchronize panes
bind-key y set-window-option synchronize-panes\; display-message "synchronize mode toggled."

# Key bindings for copy-paste
setw -g mode-keys vi
unbind p
bind p paste-buffer
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel

# Easy config reload
bind-key r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded."
